In [2]:
import numpy as np

In [3]:
a1=np.array([1,2,3])


In [4]:
print(a1)

[1 2 3]


In [5]:
arr=np.array([5,10,15,20,20,25,30])

## arr

In [6]:
# to get the unique values from thr array of the pyrthon
print(arr)


[ 5 10 15 20 20 25 30]


In [7]:
unique=np.unique(arr)

In [8]:
unique


array([ 5, 10, 15, 20, 25, 30])

In [9]:
# to find the standard deviation of the elements in arrat

In [10]:
sd=np.std(arr)

In [11]:
sd

7.953949089757175

In [12]:
# to gethe maximum

In [13]:
maximum=arr.max()

In [14]:
maximum

30

In [15]:
minimum=arr.min()

In [16]:
minimum

5

In [17]:
newarr=np.array([1,2,3,4,5,6,7])

In [18]:
newarr

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
arr+newarr

array([ 6, 12, 18, 24, 25, 31, 37])

In [20]:
arr

array([ 5, 10, 15, 20, 20, 25, 30])

In [21]:
print(arr**2)

[ 25 100 225 400 400 625 900]


In [22]:
# the above will print the squares of each values in the array

In [23]:
# to find the sum

In [24]:
np.sum(arr)

125

In [25]:
print(np.sum(arr**2))

2675


In [26]:
# to get the shape of the array

In [27]:
print(arr.shape)

(7,)


In [28]:
# to make it simple array will objects will have the methods like max,min and shape,ndim

In [29]:
print(arr.ndim)

1


In [30]:
# 2d arrays

In [31]:
arrd=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
arrd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
print(arrd.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:
# the above will give the transpose of the given matrix

In [35]:
print(arrd.shape)

(3, 3)


In [36]:
print(arrd.ndim)

2


In [37]:
# to access the contents of the numpy is

In [38]:
print(arrd[0][1])

2


In [39]:
print(arrd[2][2])

9


In [40]:
# important functionalities

In [41]:
dot=np.dot(arrd,arrd)

In [42]:
dot

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [43]:
arrd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# generating the random values

In [45]:
# random integer between the [0,1]

In [46]:
print(np.random.rand())

0.06389660672992481


In [47]:
# to get the matrix of the random values of desired shape

In [48]:
print(np.random.rand(3,3))

[[0.75430579 0.20730585 0.42895896]
 [0.92103588 0.20916344 0.71117509]
 [0.02505832 0.19502344 0.70442574]]


In [49]:
# generate the random integer values in numpy


In [50]:
print(np.random.randint(3,5,1))

[3]


In [51]:
# here 5 is exclusive

In [52]:
print(np.random.randint(1,10,(3,3)))

[[1 3 8]
 [1 7 7]
 [3 3 5]]


In [53]:
print(arrd.trace())

15


In [54]:
print(arrd.sum())

45


In [55]:
print(arr.max())

30


In [56]:
print(np.max(arr))

30


In [57]:
# sampling the data

In [58]:
print(np.random.choice(arr,10,replace=True))


[10 10 10 20 25 10 20 20 20 30]


In [59]:
print(np.random.choice(arr,3,replace=False))

[ 5 10 20]


In [60]:
# if we choose the replace = False we will get non repetitive array but it shpuld be less then the size of the actual array

In [61]:
# randomly shuffle the values

In [62]:
x=[1,2,3,4,5]

In [63]:
np.random.shuffle(x)

In [64]:
x

[2, 1, 5, 4, 3]

In [65]:
print(np.random.seed(42))

None


In [66]:
print(f"hello world")


hello world


In [67]:
# scipy library

In [68]:
# calculation of correction


In [69]:
# generating the samples from the distribution
# normal distribution 
# proabability dens=ity function
# cummulative distribution function
# calculating the descriptive statistics

In [70]:
# scipy and numpy are two librariws pandas were builtup on

In [71]:
# corelation is a numerical measure of statistical relationship
# the calculation of orelation was done using pearson's r-value


In [72]:
# -1,1,0 negative positive and no corelation exists